
server:
  port: 8888
  servlet:
    context-path: /api


spring:
  profiles:
    active: dev

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  #(MySQL 8.0)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/order_food_db?useUnicode=true&characterEncoding=utf-8&userSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000


  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 5000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0


  wx:
    miniapp:
      appid: wx6a720cf1987ad9bf
      secret: a6766c03f8845c940ddc9cab975455c6


mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.weapp.order_food.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-reload-cache: true
    enable-search: true
  openapi:
    title:
    description: " Spring Boot 2.7.15 + MyBatis-Plus + Redis "
    version: v1.0
    concat:
    url: "https://localhost:0/api/doc.html"
    group:
      default:
        group-name:
        api-rule: package
        api-rule-resources:
          - com.weapp.order_food.controller


jwt:
  secret: secure_and_long_secret_key_for_order_food_app_2026
  expiration: 604800000
  header: Authorization


